import 'reflect-metadata';
import { plainToInstance } from 'class-transformer';
import { validateSync } from 'class-validator';
import { WebhookEventDto } from '../../dto/webhook-event.dto';

import * as fs from 'fs';
import * as path from 'path';

describe('WebhookEventDto Contract', () => {
  it('should validate a payload matching DTP ExecutionEventMapper output', () => {
    // Read the actual fixture generated by DTP's ExecutionEventMapper
    const fixturePath = path.join(__dirname, 'webhook-event-fixture.json');
    const fixtureContent = fs.readFileSync(fixturePath, 'utf-8');

    // Parse it exactly as it would come over the wire
    const dtpPayload = JSON.parse(fixtureContent);

    const instance = plainToInstance(WebhookEventDto, dtpPayload);
    const errors = validateSync(instance);

    // Detailed error logging for debugging if it fails
    if (errors.length > 0) {
      console.error(errors);
    }
    expect(errors.length).toBe(0);
  });
});
